/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HOME
 */
public class TiempoApplet extends javax.swing.JFrame {

    /**
     * Initializes the applet TiempoApplet
     */
    public TiempoApplet() {
        initComponents();
    }

    public void init() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TiempoApplet.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TiempoApplet.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TiempoApplet.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TiempoApplet.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        txtMinutos = new javax.swing.JTextField();
        txtSegundos = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("Horas - Minutos y Segundos ");
        jLabel1.setBounds(20, 20, 300, 30);
        getContentPane().add(jLabel1);

        jLabel2.setText("Ingrese la Cantidad de días:");
        jLabel2.setBounds(20, 70, 210, 25);
        getContentPane().add(jLabel2);
        txtDias.setBounds(235, 70, 60, 27);
        getContentPane().add(txtDias);
        btnCalcular.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        btnCalcular.setBounds(150, 115, 130, 35);
        getContentPane().add(btnCalcular);

        jLabel3.setText("HORAS:");
        jLabel3.setBounds(20, 175, 90, 25);
        getContentPane().add(jLabel3);

        jLabel4.setText("MINUTOS:");
        jLabel4.setBounds(20, 215, 90, 25);
        getContentPane().add(jLabel4);

        jLabel5.setText("SEGUNDOS:");
        jLabel5.setBounds(20, 255, 90, 25);
        getContentPane().add(jLabel5);

        txtHoras.setEditable(false);
        txtHoras.setBounds(115, 175, 140, 25);
        getContentPane().add(txtHoras);

        txtMinutos.setEditable(false);
        txtMinutos.setBounds(115, 215, 140, 25);
        getContentPane().add(txtMinutos);

        txtSegundos.setEditable(false);
        txtSegundos.setBounds(115, 255, 140, 25);
        getContentPane().add(txtSegundos);

        lblResultado.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblResultado.setBounds(20, 305, 400, 30);
        getContentPane().add(lblResultado);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCalcularActionPerformed
        try {
            int dias = Integer.parseInt(txtDias.getText());
            int horas = dias * 24;
            int minutos = horas * 60;
            int segundos = minutos * 60;

            txtHoras.setText(String.valueOf(horas));
            txtMinutos.setText(String.valueOf(minutos));
            txtSegundos.setText(String.valueOf(segundos));

            lblResultado.setText(
                    dias + " días tienen " + horas + " horas, " + minutos + " minutos y " + segundos + " segundos.");
        } catch (NumberFormatException e) {
            lblResultado.setText("Por favor, ingrese un número de días válido.");
        }
    }// GEN-LAST:event_btnCalcularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtMinutos;
    private javax.swing.JTextField txtSegundos;

    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TiempoApplet frame = new TiempoApplet();
                frame.setSize(450, 430);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }
}
