/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class FacturaApplet extends javax.swing.JApplet {

    /**
     * Initializes the applet FacturaApplet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProd1 = new javax.swing.JTextField();
        txtProd3 = new javax.swing.JTextField();
        txtPrecio1 = new javax.swing.JTextField();
        txtProd2 = new javax.swing.JTextField();
        txtPrecio2 = new javax.swing.JTextField();
        txtPrecio3 = new javax.swing.JTextField();
        txtCant2 = new javax.swing.JTextField();
        txtTotal1 = new javax.swing.JTextField();
        txtTotal2 = new javax.swing.JTextField();
        txtTotal3 = new javax.swing.JTextField();
        txtCant1 = new javax.swing.JTextField();
        txtCant3 = new javax.swing.JTextField();
        txtTotalFactura = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ORDEN DE COMPRA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Cliente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtCliente.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 204, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Producto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 91, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Vlr.Unitario");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 91, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 91, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Vlr. Total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 91, -1, -1));

        txtProd1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        getContentPane().add(txtProd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, 123, -1));

        txtProd3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        getContentPane().add(txtProd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 123, -1));

        txtPrecio1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtPrecio1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 112, 119, -1));

        txtProd2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        getContentPane().add(txtProd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 139, 123, -1));

        txtPrecio2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtPrecio2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 139, 119, -1));

        txtPrecio3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtPrecio3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 166, 119, -1));

        txtCant2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtCant2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 139, 66, -1));

        txtTotal1.setEditable(false);
        txtTotal1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtTotal1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 112, 82, -1));

        txtTotal2.setEditable(false);
        txtTotal2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtTotal2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 139, 82, -1));

        txtTotal3.setEditable(false);
        txtTotal3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtTotal3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 166, 82, -1));

        txtCant1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        txtCant1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 112, 66, -1));

        txtCant3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCant3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCant3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtCant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 167, 66, -1));

        txtTotalFactura.setEditable(false);
        txtTotalFactura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txtTotalFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 205, 82, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Valor Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 207, -1, -1));

        lblResultado.setText("Resumen de Compra...");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 264, 444, -1));

        btnCalcular.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 318, 113, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCant3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCant3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCant3ActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
          try {
        String nombreCliente = txtCliente.getText();
        int precio1 = Integer.parseInt(txtPrecio1.getText());
        int cant1 = Integer.parseInt(txtCant1.getText());
        int precio2 = Integer.parseInt(txtPrecio2.getText());
        int cant2 = Integer.parseInt(txtCant2.getText());
        int precio3 = Integer.parseInt(txtPrecio3.getText());
        int cant3 = Integer.parseInt(txtCant3.getText());
        int totalProducto1 = precio1 * cant1;
        int totalProducto2 = precio2 * cant2;
        int totalProducto3 = precio3 * cant3;
        int granTotal = totalProducto1 + totalProducto2 + totalProducto3;
        txtTotal1.setText(String.valueOf(totalProducto1));
        txtTotal2.setText(String.valueOf(totalProducto2));
        txtTotal3.setText(String.valueOf(totalProducto3));
        txtTotalFactura.setText(String.valueOf(granTotal));
        lblResultado.setText("<html><span style='font-family: Serif; color: #D4AF37; text-shadow: 2px 2px 3px black; font-size: 14px;'><b>Señor(a) " + nombreCliente + ", el total de su compra es de: $" + granTotal + "</b></span></html>");
        
        } catch (NumberFormatException e) {
    lblResultado.setText("<html><span style='color: red;'><b>Error: Asegúrese de llenar todos los campos con números válidos.</b></span></html>");
    }//GEN-LAST:event_btnCalcularActionPerformed
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtCant1;
    private javax.swing.JTextField txtCant2;
    private javax.swing.JTextField txtCant3;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtPrecio3;
    private javax.swing.JTextField txtProd1;
    private javax.swing.JTextField txtProd2;
    private javax.swing.JTextField txtProd3;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JTextField txtTotal2;
    private javax.swing.JTextField txtTotal3;
    private javax.swing.JTextField txtTotalFactura;
    // End of variables declaration//GEN-END:variables
}
