/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Graphics;

/**
 *
 * @author HOME
 */
public class TrianguloApplet extends javax.swing.JFrame {

    /**
     * Creates new form TrianguloApplet
     */
    public TrianguloApplet() {
        initComponents();
    }

    public void init() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrianguloApplet.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrianguloApplet.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrianguloApplet.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrianguloApplet.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtLadoA = new javax.swing.JTextField();
        txtLadoB = new javax.swing.JTextField();
        txtLadoC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAnguloA = new javax.swing.JTextField();
        txtAnguloB = new javax.swing.JTextField();
        txtAnguloC = new javax.swing.JTextField();
        txtArea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        btnEjecutar = new javax.swing.JButton();
        panelDibujo = new javax.swing.JPanel();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("TRIÁNGULOS");
        jLabel1.setBounds(286, 11, 350, 30);
        getContentPane().add(jLabel1);

        jLabel2.setText("A:");
        jLabel2.setBounds(10, 87, 110, 25);
        getContentPane().add(jLabel2);

        jLabel3.setText("B:");
        jLabel3.setBounds(10, 150, 110, 25);
        getContentPane().add(jLabel3);

        jLabel4.setText("C:");
        jLabel4.setBounds(10, 213, 110, 25);
        getContentPane().add(jLabel4);

        txtLadoA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLadoA.setBounds(57, 81, 75, 25);
        getContentPane().add(txtLadoA);

        txtLadoB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLadoB.setBounds(57, 144, 75, 25);
        getContentPane().add(txtLadoB);

        txtLadoC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLadoC.setBounds(57, 207, 75, 25);
        getContentPane().add(txtLadoC);

        jLabel5.setText("ALTURA:");
        jLabel5.setBounds(10, 276, 110, 25);
        getContentPane().add(jLabel5);

        txtAltura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAltura.setBounds(57, 270, 75, 25);
        getContentPane().add(txtAltura);

        jLabel6.setText("ÁREA:");
        jLabel6.setBounds(162, 273, 110, 25);
        getContentPane().add(jLabel6);

        jLabel7.setText("ÁNGULO A:");
        jLabel7.setBounds(162, 84, 110, 25);
        getContentPane().add(jLabel7);

        jLabel8.setText("ÁNGULO C:");
        jLabel8.setBounds(162, 210, 110, 25);
        getContentPane().add(jLabel8);

        jLabel9.setText("ÁNGULO B:");
        jLabel9.setBounds(162, 147, 110, 25);
        getContentPane().add(jLabel9);

        txtAnguloA.setEditable(false);
        txtAnguloA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnguloA.setBounds(235, 81, 104, 25);
        getContentPane().add(txtAnguloA);

        txtAnguloB.setEditable(false);
        txtAnguloB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnguloB.setBounds(234, 144, 105, 25);
        getContentPane().add(txtAnguloB);

        txtAnguloC.setEditable(false);
        txtAnguloC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAnguloC.setBounds(235, 207, 104, 25);
        getContentPane().add(txtAnguloC);

        txtArea.setEditable(false);
        txtArea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArea.setBounds(235, 270, 104, 25);
        getContentPane().add(txtArea);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("TIPO DE TRIÁNGULO");
        jLabel10.setBounds(479, 48, 110, 25);
        getContentPane().add(jLabel10);

        txtTipo.setEditable(false);
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoActionPerformed(evt);
            }
        });
        txtTipo.setBounds(479, 81, 123, 25);
        getContentPane().add(txtTipo);

        btnEjecutar.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnEjecutar.setText("EJECUTAR");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        btnEjecutar.setBounds(292, 331, 111, 37);
        getContentPane().add(btnEjecutar);

        panelDibujo.setOpaque(false);

        javax.swing.GroupLayout panelDibujoLayout = new javax.swing.GroupLayout(panelDibujo);
        panelDibujo.setLayout(panelDibujoLayout);
        panelDibujoLayout.setHorizontalGroup(
                panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 204, Short.MAX_VALUE));
        panelDibujoLayout.setVerticalGroup(
                panelDibujoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 195, Short.MAX_VALUE));

        panelDibujo.setBounds(436, 127, 210, 200);
        getContentPane().add(panelDibujo);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTipoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTipoActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEjecutarActionPerformed
        try {
            double a = Double.parseDouble(txtLadoA.getText());
            double b = Double.parseDouble(txtLadoB.getText());
            double c = Double.parseDouble(txtLadoC.getText());
            double h = Double.parseDouble(txtAltura.getText());
            String tipo = "";
            int tipoCodigo = 0;

            if (a == b && b == c) {
                tipo = "Equilátero";
                tipoCodigo = 1;
            } else if (a == b || b == c || a == c) {
                tipo = "Isósceles";
                tipoCodigo = 2;
            } else {
                tipo = "Escaleno";
                tipoCodigo = 3;
            }
            double anguloA = 0;
            double anguloB = 0;
            double anguloC = 0;
            switch (tipoCodigo) {
                case 1:
                    anguloA = 60.0;
                    anguloB = 60.0;
                    anguloC = 60.0;
                    break;
                case 2:
                    double cosA_iso = (b * b + c * c - a * a) / (2.0 * b * c);
                    anguloA = Math.toDegrees(Math.acos(cosA_iso));

                    double cosB_iso = (a * a + c * c - b * b) / (2.0 * a * c);
                    anguloB = Math.toDegrees(Math.acos(cosB_iso));

                    anguloC = 180.0 - (anguloA + anguloB);
                    break;
                case 3:
                    double cosA_esc = (b * b + c * c - a * a) / (2.0 * b * c);
                    anguloA = Math.toDegrees(Math.acos(cosA_esc));

                    double cosB_esc = (a * a + c * c - b * b) / (2.0 * a * c);
                    anguloB = Math.toDegrees(Math.acos(cosB_esc));

                    anguloC = 180.0 - (anguloA + anguloB);
                    break;
            }
            double area = (c * h) / 2.0;
            txtTipo.setText(tipo);
            txtArea.setText(String.format("%.2f", area));
            txtAnguloA.setText(String.format("%.2f°", anguloA));
            txtAnguloB.setText(String.format("%.2f°", anguloB));
            txtAnguloC.setText(String.format("%.2f°", anguloC));
            Graphics g = panelDibujo.getGraphics();
            panelDibujo.update(g);
            int centroX = panelDibujo.getWidth() / 2;
            int centroY = panelDibujo.getHeight() / 2;

            if (tipoCodigo == 1) {
                int[] xPoints = { centroX, centroX - 60, centroX + 60 };
                int[] yPoints = { centroY - 50, centroY + 50, centroY + 50 };
                g.drawPolygon(xPoints, yPoints, 3);
            } else if (tipoCodigo == 2) {
                int[] xPoints = { centroX, centroX - 40, centroX + 40 };
                int[] yPoints = { centroY - 65, centroY + 55, centroY + 55 };
                g.drawPolygon(xPoints, yPoints, 3);
            } else {
                int[] xPoints = { centroX - 20, centroX - 65, centroX + 55 };
                int[] yPoints = { centroY - 50, centroY + 45, centroY + 25 };
                g.drawPolygon(xPoints, yPoints, 3);
            }

        } catch (NumberFormatException e) {
            txtTipo.setText("Error en datos");
        }
    }// GEN-LAST:event_btnEjecutarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelDibujo;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtAnguloA;
    private javax.swing.JTextField txtAnguloB;
    private javax.swing.JTextField txtAnguloC;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtLadoA;
    private javax.swing.JTextField txtLadoB;
    private javax.swing.JTextField txtLadoC;
    private javax.swing.JTextField txtTipo;

    // End of variables declaration//GEN-END:variables
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TrianguloApplet frame = new TrianguloApplet();
                frame.setSize(720, 450);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }
}
