/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HOME
 */
public class AA4_EV02_Ciclos extends javax.swing.JFrame {
    public AA4_EV02_Ciclos() {
        initComponents();
    }

    /**
     * Initializes the applet AA4_EV02_Ciclos
     */

    public void init() {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AA4_EV02_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AA4_EV02_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AA4_EV02_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AA4_EV02_Ciclos.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOpcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        btnEjecutar = new javax.swing.JButton();

        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROMEDIO NOTAS");
        jLabel1.setBounds(150, 25, 320, 35);
        getContentPane().add(jLabel1);

        jLabel2.setText("1. Matemáticas  2. Español  3.Inglés ");
        jLabel2.setBounds(30, 140, 350, 25);
        getContentPane().add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("SELECCIONE UNA MATERIA:");
        jLabel3.setBounds(30, 110, 260, 25);
        getContentPane().add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("CANTIDAD DE ESTUDIANTES:");
        jLabel4.setBounds(30, 195, 260, 25);
        getContentPane().add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("RESULTADO DEL PROMEDIO:");
        jLabel5.setBounds(30, 260, 260, 25);
        getContentPane().add(jLabel5);

        txtOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOpcionActionPerformed(evt);
            }
        });
        txtOpcion.setBounds(310, 110, 80, 28);
        getContentPane().add(txtOpcion);
        txtCantidad.setBounds(310, 195, 80, 28);
        getContentPane().add(txtCantidad);

        lblResultado.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblResultado.setText("0.0");
        lblResultado.setBounds(310, 260, 140, 28);
        getContentPane().add(lblResultado);

        btnEjecutar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        btnEjecutar.setText("CALCULAR");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        btnEjecutar.setBounds(270, 325, 180, 45);
        getContentPane().add(btnEjecutar);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOpcionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtOpcionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtOpcionActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEjecutarActionPerformed

        try {
            int materia = Integer.parseInt(txtOpcion.getText());
            int cantidad = Integer.parseInt(txtCantidad.getText());
            double sumaNotas = 0;
            double nota;
            double promedio;
            switch (materia) {

                case 1:
                    for (int i = 1; i <= cantidad; i++) {
                        String entrada = javax.swing.JOptionPane
                                .showInputDialog("MATEMÁTICAS\nIngrese nota del estudiante " + i);
                        nota = Double.parseDouble(entrada);
                        sumaNotas = sumaNotas + nota;
                    }
                    break;

                case 2:
                    int cWhile = 1;
                    while (cWhile <= cantidad) {
                        String entrada = javax.swing.JOptionPane
                                .showInputDialog("ESPAÑOL\nIngrese nota del estudiante " + cWhile);
                        nota = Double.parseDouble(entrada);
                        sumaNotas = sumaNotas + nota;
                        cWhile++;
                    }
                    break;

                case 3:
                    int cDo = 1;
                    do {
                        String entrada = javax.swing.JOptionPane
                                .showInputDialog("INGLÉS\nIngrese nota del estudiante " + cDo);
                        nota = Double.parseDouble(entrada);
                        sumaNotas = sumaNotas + nota;
                        cDo++;
                    } while (cDo <= cantidad);
                    break;

                default:
                    javax.swing.JOptionPane.showMessageDialog(null, "Opción de materia no válida");
                    return;
            }
            promedio = sumaNotas / cantidad;
            lblResultado.setText(String.valueOf(promedio));

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Error: Verifique que ingresó números válidos.");
        }
    }// GEN-LAST:event_btnEjecutarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtOpcion;
    // End of variables declaration//GEN-END:variables

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AA4_EV02_Ciclos frame = new AA4_EV02_Ciclos();
                frame.setSize(580, 460);
                frame.setLocationRelativeTo(null);
                frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }
}
